In [2]:
import pandas as pd
import numpy as np

In [3]:
# быстро создаем объект DataFrame
def make_df(cols, ind):
    data = {
        c: [str(c) + str(i) for i in ind]
        for c in cols   
           }
    return pd.DataFrame(data, ind)
make_df("ABC", range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

## Объединение наборов данных

In [13]:
# конкатенация массивов NumPy
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
print(np.concatenate([x, y, z]))
x = [[1, 2], [3, 4]]
print(np.concatenate([x, x], axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 2 1 2]
 [3 4 3 4]]


In [15]:
# простая конкатенация (pd.concat)
# Сигнатура функции:
# pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, copy=True)
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])  # по умолчанию axis=0

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [22]:
df1 = make_df("ABC", range(3))
df2 = make_df("DEF", range(3))
pd.concat([df1, df2], axis=1)

A   B   C   D   E   F
0  A0  B0  C0  D0  E0  F0
1  A1  B1  C1  D1  E1  F1
2  A2  B2  C2  D2  E2  F2

In [26]:
# конкатенация с использованием соединений
df3 = make_df("ABC", [1, 2])
df4 = make_df("BCD", [3, 4])
print(pd.concat([df3, df4]))  # по умолчанию join='outer'
print("inner join:")
print(pd.concat([df3, df4], join='inner'))


     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
inner join:
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
outer join:
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [29]:
# метод append()
df1.append(df2)  # аналог pd.concat([df1, df2])

A    B    C    D    E    F
0   A0   B0   C0  NaN  NaN  NaN
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2  NaN  NaN  NaN
0  NaN  NaN  NaN   D0   E0   F0
1  NaN  NaN  NaN   D1   E1   F1
2  NaN  NaN  NaN   D2   E2   F2

## Слияние и соединение

функция pd.merge()

типы соединений:
1. один-к-одному
2. многие-к-одному
3. многие-ко-многим

In [40]:
# соединение один-к-одному (напоминает конкатенацию по столбцам)
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)
df3 = pd.merge(df1, df2)
print(df3)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [42]:
# соединение многие-к-одному (один из двух ключевых столбцов содержит дублирующие значения)
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4)
pd.merge(df3, df4)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [45]:
# соединение многие-ко-многим

df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})
print(df1); print(df5)
pd.merge(df1, df5)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

### Задание ключа слияния 

In [47]:
# ключевое слово 'on' - указывается название или список названий столбцов
print(df1); print(df2)
pd.merge(df1, df2, on='employee')

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [53]:
# ключевые слова left_on и right_on - для слияния наборов данных с различными именам столбцов
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
print(df1); print(df3)
res = pd.merge(df1, df3, left_on='employee', right_on='name')  # будет избыточный столбец, чтобы убрать .drop()
res.drop('name', axis=1)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [57]:
# ключевые слова left_index и right_index (использование индекса в качестве ключа слияния)
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a); print(df2a)
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

# метод join() - слияние по индексу
print(df1a.join(df2a))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014


In [58]:
# комбинация слияния по столбцам и индексам
pd.merge(df1a, df3, left_index=True, right_on='name')

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

## Задание операций над множеставами для соединений 

In [8]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
print(df6); print(df7)

print("\nпо умолчанию - inner join")
print(pd.merge(df6, df7))

print("\nouter join")
print(pd.merge(df6, df7, how='outer'))

print("\nleft join")
print(pd.merge(df6, df7, how='left'))

print("\nright join")
print(pd.merge(df6, df7, how='right'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer

по умолчанию - inner join
   name   food drink
0  Mary  bread  wine

outer join
     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

left join
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

right join
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer


###  Пересекающиеся названия стобцов: ключевое слово suffixes

In [10]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
print(df8); print(df9)

print('\nпо умолчанию суффиксы _x и _y')
print(pd.merge(df8, df9, on="name"))

print('\nзададим собственные суффиксы')
print(pd.merge(df8, df9, on='name', suffixes=["_L", "_R"]))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

по умолчанию суффиксы _x и _y
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

зададим собственные суффиксы
   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2
