In [18]:
import numpy as np
np.__version__


### Атрибуты массивов 

In [24]:
x1 = np.random.randint(10, size = (5))
x2 = np.random.randint(10, size = (2, 2))
x3 = np.random.randint(10, size = (3, 3, 3))
x3

array([[[4, 8, 5],
        [0, 0, 8],
        [9, 6, 1]],

       [[2, 5, 9],
        [5, 9, 0],
        [7, 7, 1]],

       [[8, 5, 5],
        [3, 9, 2],
        [8, 1, 1]]])

In [21]:
x3.ndim # размерность
x3.size # общий размер массива
x3.shape # размер каждого измерения
x3.dtype # тип данных массива
x3.itemsize # размер (в байтах) каждого элемента массива
x3.nbytes # полный размер массива (в байтах)


In [26]:
x3.size * x3.itemsize
x3.nbytes

108

In [34]:
x3[0, 0, 0] == x3[0][0][0]

True

In [28]:
x3[:, :, 1:2] # вывести только средний столбец
x3[:, :, ::2] # каждый второй столбец

array([[[4, 5],
        [0, 8],
        [9, 1]],

       [[2, 9],
        [5, 0],
        [7, 1]],

       [[8, 5],
        [3, 2],
        [8, 1]]])

In [61]:
x3 = np.random.randint(10, size = (4, 4))
x3

array([[9, 4, 0, 7],
       [1, 0, 6, 4],
       [2, 5, 8, 5],
       [7, 1, 9, 2]])

In [66]:
x3_copy = x3[:, 1::2].copy()
x3_copy[0] = [7, 4]
x3_copy

array([[7, 4],
       [0, 4],
       [5, 5],
       [1, 2]])

In [29]:
grid = np.eye(3, dtype='int32')
grid = grid.reshape(9)

In [30]:
x = np.arange(10).reshape((1, 10))
x = np.arange(10).reshape((10, 1))
# или 
x = np.arange(10)
x[np.newaxis, :]
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Слияние и разбиение 

In [95]:
x = np.arange(10)
y = np.arange(10, 20)
z = np.arange(20, 30)
np.concatenate([x, y, z])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [97]:
np.concatenate([x, x])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([x, x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [105]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y1 = np.array([7, 8, 9])
y2 = np.array([[99], [99]])
np.vstack([x, y1]) # объединить по вертикали
np.hstack([x, y2]) # объединить по горизонтали


array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [31]:
x = np.array([1, 2, 3, 99, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, 3)
print(x1, x2, x3)
x1, x2, x3 = np.split(x, [3,6])
print(x1, x2, x3)

[1 2 3] [99 99 99] [3 2 1]
[1 2 3] [99 99 99] [3 2 1]


In [32]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
left, right = np.hsplit(grid, [2])
print('grid = \n', grid)
print('upper = \n', upper, '\nlower = \n', lower)
print('left = \n', left, '\nright = \n', right)
np.vsplit?

grid = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
upper = 
 [[0 1 2 3]
 [4 5 6 7]] 
lower = 
 [[ 8  9 10 11]
 [12 13 14 15]]
left = 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
right = 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
