In [99]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn

## Сортировка массивов 

### Сортировка вставкой 

In [6]:
x = np.random.randint(0, 10, 10)
print(x)
for i in range(len(x)):
    swap = i + np.argmin(x[i:])
    x[i], x[swap] = x[swap], x[i]
print(x)

[4 6 5 1 0 1 8 9 4 1]
[0 1 1 1 4 4 5 6 8 9]


### Случайная сортировка 

In [8]:
x = np.random.randint(0, 10, 10)
print(x)
while np.any(x[:-1] > x[1:]):
    np.random.shuffle(x)
print(x)

[9 6 8 2 3 1 8 1 9 3]
[1 1 2 3 3 6 8 8 9 9]


### Быстрая сортировка 

In [94]:
x = np.random.randint(0, 10, 10)
print(x)
%timeit np.sort(x)
%timeit x.sort()
x

[4 4 2 5 1 5 1 4 1 5]
1.3 µs ± 5.87 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
277 ns ± 5.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


array([1, 1, 1, 2, 4, 4, 4, 5, 5, 5])

In [16]:
ind = np.argsort(x)
x[ind]

array([1, 2, 3, 5, 7, 7, 8, 8, 8, 9])

In [24]:
x = np.random.randint(0, 10, size = (4, 6))
print(x)

[[1 3 8 4 4 0]
 [9 3 6 5 9 8]
 [4 2 0 5 3 0]
 [2 6 7 9 6 9]]


In [26]:
np.sort(x, axis = 1) # сортировка по строкам

array([[0, 1, 3, 4, 4, 8],
       [3, 5, 6, 8, 9, 9],
       [0, 0, 2, 3, 4, 5],
       [2, 6, 6, 7, 9, 9]])

In [28]:
np.sort(x, axis = 0) # сортировка по столбцам

array([[1, 2, 0, 4, 3, 0],
       [2, 3, 6, 5, 4, 0],
       [4, 3, 7, 5, 6, 8],
       [9, 6, 8, 9, 9, 9]])

### Частичные сортировки: секционирование 

In [35]:
np.partition(x, 3, axis = 1)

array([[0, 1, 3, 4, 4, 8],
       [5, 6, 3, 8, 9, 9],
       [0, 0, 2, 3, 4, 5],
       [6, 2, 6, 7, 9, 9]])

In [97]:
np.argpartition(x, 3)

array([2, 1, 0, 3, 6, 4, 5, 7, 8, 9], dtype=int64)