In [15]:
import numpy as np

In [6]:
x = np.arange(10)
y = np.arange(10, 20)
z = np.linspace(0, 1, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x = np.arange(1, 6)
np.add.reduce(x)
np.multiply.reduce(x)
np.add.accumulate(x) # = np.cumsum(x)
np.multiply.accumulate(x) # = np.cumproduct(x)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3, 4])
x = np.multiply.outer(a, b)
x

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16],
        [ 5, 10, 15, 20],
        [ 6, 12, 18, 24]]])

### Агрегирование 

In [34]:
L = np.random.random(100)
%timeit sum(L)
%timeit np.sum(L)
%timeit L.sum()

6.41 µs ± 54.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.84 µs ± 30.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.13 µs ± 6.71 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [37]:
np.min(L)
L.min()
np.max(L) == L.max()

True

In [39]:
M = np.random.random((3, 4))
M

array([[0.10282566, 0.35308966, 0.17745314, 0.64274831],
       [0.15803948, 0.96137614, 0.0144    , 0.83424533],
       [0.92114889, 0.75628817, 0.09410283, 0.44997971]])

In [44]:
M.sum(axis = 0) # axis - ось, по которой вычисляется сводный показатель (axis = 0 - по столбцам)

array([1.18201403, 2.07075397, 0.28595596, 1.92697334])

In [46]:
M.sum(axis = 1) # сумма по строкам

array([1.27611677, 1.96806095, 2.22151959])

### Другие функции агрегирования 

In [64]:
# np.sum, np.prod, np.min, np.max ранее рассмотрены
np.mean(L) # среднее значение
np.std(L) # стандартное отклонение
np.var(L) # дисперсия
np.argmax(L) # индекс макс значения
np.argmin(L) # индекс мин значения
np.median(L) # медиана
np.percentile(L, 25)
np.percentile(L, 75)
np.any(L) # существуют ли элемененты со значением True
np.all(L) # все ли элементы True

True

### Пример 

In [77]:
heights = np.random.randint(163, 194, 43)
print(f"Среднее значение роста = {heights.mean()}")
print(f"Минимальное значение роста = {heights.min()}")
print(f"Максимальное значение роста = {heights.max()}")
print(f"Стандартное отклонение = {heights.std()}")
print(f"Медиана = {np.median(heights)}")

Среднее значение роста = 179.48837209302326
Минимальное значение роста = 163
Максимальное значение роста = 193
Стандартное отклонение = 8.702771793216376
Медиана = 179.0
